from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1280, 720)
        mainWindow.setStyleSheet("#main{background-color: rgb(0, 0, 0); border-radius: 12px;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QWidget(mainWindow)
        self.main.setStyleSheet("")
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu = QtWidgets.QWidget(self.main)
        self.menu.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu.setObjectName("menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_1 = QtWidgets.QWidget(self.menu)
        self.menu_1.setObjectName("menu_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menu_1)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.appName = QtWidgets.QLabel(self.menu_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.appName.setFont(font)
        self.appName.setStyleSheet("color: rgb(255, 255, 255);")
        self.appName.setObjectName("appName")
        self.horizontalLayout_2.addWidget(self.appName)
        self.hide = QtWidgets.QPushButton(self.menu_1)
        self.hide.setMaximumSize(QtCore.QSize(20, 20))
        self.hide.setStyleSheet("background-color: rgb(106, 106, 106); border-radius: 10px;")
        self.hide.setText("")
        self.hide.setObjectName("hide")
        self.horizontalLayout_2.addWidget(self.hide)
        self.minMax = QtWidgets.QPushButton(self.menu_1)
        self.minMax.setMaximumSize(QtCore.QSize(20, 20))
        self.minMax.setStyleSheet("background-color: rgb(106, 106, 106); border-radius: 10px;")
        self.minMax.setText("")
        self.minMax.setObjectName("minMax")
        self.horizontalLayout_2.addWidget(self.minMax)
        self._close = QtWidgets.QPushButton(self.menu_1)
        self._close.setMaximumSize(QtCore.QSize(20, 20))
        self._close.setStyleSheet("background-color: rgb(127, 0, 0); border-radius: 10px;")
        self._close.setText("")
        self._close.setObjectName("_close")
        self.horizontalLayout_2.addWidget(self._close)
        self.verticalLayout_3.addWidget(self.menu_1)
        self.menu_2 = QtWidgets.QWidget(self.menu)
        self.menu_2.setObjectName("menu_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu_2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.menu_2)
        self.back.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(0, 0, 0); color: rgb(255, 255, 255);")
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        self.forward = QtWidgets.QPushButton(self.menu_2)
        self.forward.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.forward.setFont(font)
        self.forward.setStyleSheet("background-color: rgb(0, 0, 0); color: rgb(255, 255, 255);")
        self.forward.setObjectName("forward")
        self.horizontalLayout.addWidget(self.forward)
        self.reboot = QtWidgets.QPushButton(self.menu_2)
        self.reboot.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.reboot.setFont(font)
        self.reboot.setStyleSheet("background-color: rgb(0, 0, 0); color: rgb(255, 255, 255);")
        self.reboot.setObjectName("reboot")
        self.horizontalLayout.addWidget(self.reboot)
        self.www = QtWidgets.QLineEdit(self.menu_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.www.setFont(font)
        self.www.setStyleSheet("background-color: rgb(72, 72, 72); color: rgb(255, 255, 255); border: none;")
        self.www.setText("")
        self.www.setObjectName("www")
        self.horizontalLayout.addWidget(self.www)
        self.verticalLayout_3.addWidget(self.menu_2)
        self.verticalLayout_2.addWidget(self.menu)
        self.web = QtWebEngineWidgets.QWebEngineView(self.main)
        self.web.setObjectName("web")
        self.web.page().setBackgroundColor(QtGui.QColor("#000"))
        self.verticalLayout_2.addWidget(self.web)
        self.verticalLayout.addWidget(self.main)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Form"))
        self.appName.setText(_translate("mainWindow", "PBrowser"))
        self.back.setText(_translate("mainWindow", "🡄"))
        self.forward.setText(_translate("mainWindow", "🡆"))
        self.reboot.setText(_translate("mainWindow", "⭯"))
